# Generated by Django 3.0.6 on 2020-05-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arhivska_Tabela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broj_zalivanja', models.IntegerField(default=0)),
                ('prosecna_temperatura', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prosecna_vlaznost_vazduha', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prosecni_vazdusni_pritisak', models.DecimalField(decimal_places=2, max_digits=15)),
                ('prosecna_vlaznost_zemljista', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Dnevna_Tabela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('temperatura', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vlaznost_vazduha', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vazdusni_pritisak', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vlaznost_zemljista', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
