# Generated by Django 3.0.6 on 2020-05-20 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arhivska_tabela',
            name='datum',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
