# Generated by Django 3.0.6 on 2020-05-20 16:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0002_arhivska_tabela_datum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnevna_tabela',
            name='datum',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
