# Generated by Django 3.0.6 on 2020-06-07 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0004_auto_20200521_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arhivskatabela',
            old_name='prosecni_vazdusni_pritisak',
            new_name='prosek_kisa',
        ),
        migrations.RenameField(
            model_name='dnevnatabela',
            old_name='vazdusni_pritisak',
            new_name='kisa',
        ),
    ]
