# Generated by Django 3.0.6 on 2020-06-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basta', '0005_auto_20200607_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnevnatabela',
            name='otvoren_prozor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dnevnatabela',
            name='radi_ventilator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dnevnatabela',
            name='zalivanje',
            field=models.BooleanField(default=False),
        ),
    ]
